#Rushland configuration

#Configure your key & slots (keys = main|lobby|pvp)
plugin:
 key: main
 slots: -1

#Configure your mysql database connection
database:
 host: 127.0.0.1
 name: rushland
 user: root
 pass: